platform :ios, '13.3'
use_frameworks!

target 'TiltUp_Example' do
  pod 'SwiftLint'

  pod 'TiltUp', path: '../'

  target 'TiltUp_Tests' do
    inherit! :search_paths

    pod 'TiltUpTest', path: '../'
  end
end
