# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do 
  cocoapods(podfile: './Example/PodApp/Podfile')
end

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(workspace: "Example/PodApp/TiltUp.xcworkspace", scheme: "TiltUp-Example", device: "iPhone 8", clean: true)
  end
end
